### ISSUE TITLE
variable clientRequest is already defined in method send

### ISSUE THREAD

**Issue by stevehu** [networknt/light-consumer-4j#16]
This is captured by the automatic build process as a compile error. 

```
HttpClientBuilder.java:72: error: variable clientRequest is already defined in method send()
            ClientRequest clientRequest = httpClientRequest.getClientRequest();

```

**Comment by NicholasAzar** [comment]
@stevehu thanks for the fix, looks like this was introduced in #14 and i missed it.
Would you be able to setup a pr check for this repo?

**Comment by stevehu** [comment]
PR check only works for the master branch as we have dependencies that are not released. All existing CI/CD tools only support individual repository and expect all dependencies can be downloaded from maven central. This is only of the reasons we have built light-bot. I think it would be very easy to build a microservice that support webhook and calling light-bot for the check.
